services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spacexdb
    networks:
      - app-tier
  app:
    build: ./app/
    depends_on:
      - "db"
    networks:
      - app-tier      
networks:
  app-tier:
    driver: bridge