services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spacexdb
      volumes:
        - ./db-data/:/var/lib/postgresql/data/
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build: ./app/