services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spacexdb
      volumes:
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to showcases tables
          - ./sql/showcases.sql:/docker-entrypoint-initdb.d/showcases.sql
  app:
    build: ./app/